# Generated by Django 3.2.4 on 2021-06-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploads', '0004_auto_20210616_1836'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='uploads.uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result',
            field=models.TextField(blank=True),
        ),
    ]
