# Generated by Django 3.2.4 on 2021-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0002_auto_20210616_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='reports'),
        ),
    ]
