# Generated by Django 3.2.4 on 2021-06-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0005_alter_report_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.AddField(
            model_name='report',
            name='face_sample',
            field=models.ImageField(blank=True, default='no-img.png', upload_to='reports'),
        ),
        migrations.AddField(
            model_name='report',
            name='fake_frame_graph',
            field=models.ImageField(blank=True, default='no-img.png', upload_to='reports'),
        ),
        migrations.AddField(
            model_name='report',
            name='frame_graph',
            field=models.ImageField(blank=True, default='no-img.png', upload_to='reports'),
        ),
        migrations.AddField(
            model_name='report',
            name='no_of_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pred_mean',
            field=models.TextField(blank=True),
        ),
    ]
