# Generated by Django 3.2.4 on 2021-06-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0006_auto_20210617_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='face_sample',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='fake_frame_graph',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='frame_graph',
            field=models.TextField(blank=True),
        ),
    ]
