# Generated by Django 3.2.4 on 2021-06-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210617_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='fake_frame_graph',
            new_name='frame_pred_graph',
        ),
    ]
