# Generated by Django 3.2.4 on 2021-06-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file_name',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
