# Generated by Django 3.2.4 on 2021-06-16 19:02

from django.db import migrations, models

import uploads.utils


class Migration(migrations.Migration):
    dependencies = [
        ('uploads', '0004_auto_20210616_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='changed_file_name',
            field=models.FileField(default='admin_2021-06-16_18-43-14.mp4', upload_to=uploads.utils.path_and_rename),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploads',
            name='file_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
